### ISSUE TITLE
Extensible labels to cover issues status changes

### ISSUE THREAD

**Issue by dsimansk** [redhat-ipaas/pure-bot#16]
Since GH issues, nor ZenHub extension don't provide extensive set of status values that could be used similarly to Jira. I've a proposal to implement additional labelling by the Pure bot. 

I've in mind especially `unverified/ready to qe` status or set `resolved` and then close manually maybe. That would enable clear filtering what should be checked after PR was provided for it.

For the bot config part, probably a set of labels to apply in conjunctions with `approved` could be sufficient for now.

Wdyt @jimmidyson @rhuss? I'm all right with asking during retrospective etc. to gather more feedback.

**Comment by rhuss** [comment]
Sounds good to me, everything which helps in the process is fine to me. Now that we already have quite a bunch of feature requests for poor pure-bot, I wonder whether we should give it some love in the next sprint ? // @jimmidyson

**Comment by jimmidyson** [comment]
happy to pick it up :)

**Comment by rhuss** [comment]
Coolio

**Comment by jimmidyson** [comment]
So I'd like to get some more requirements around this. How we can move between labels as states, and what labels we require to be applied so we can auto-merge. I see syndesisio/syndesis#9 as a starter, but not rich enough.

Thoughts?

**Comment by rhuss** [comment]
I think we have to distinguish between issues and PRs. For PRs the current flow to have an approve (with some protections like you added for "WIP" labels) is already appropriate. However *when* auto-merged the corresponding issue should get some extra labels (instead of closing it, we might to even reopen it if closed by the "fixed" automatism). Or as an alternative a _new issue_ is created for a PR which carries some labels to mark it as QE relevant. 

@dsimansk could you elaborate a bit on your specific use case for QE ?

**Comment by dsimansk** [comment]
In Jira we usually move from `Resolved` -> `Closed` when issue is verified by QE. 

To mimic the similar flow on labels, it'd be probably sufficient to place `Resolved` label on issue closed by PR. And then QE could switch `Resolved` to `Verified` once it's checked.
Imho we don't even need to bend GH's autoclose mechanism, as the issues needed verification could be filtered by `Resolved` and then switched to `Verified` manually or reopened.

**Comment by heiko-braun** [comment]
The bot now supports moving issues on a zenhub board and can mirror the above use cases. closing this one.
